Us1 header
WildCodeSchool/tours-php-2009-project3-wewelcome pull request #1
Opened 2020-12-10 08:44 UTC by FLorianBlm

Html header and footer on base.html.twig

2020-12-10 09:08 UTC, Quentin-BLANC submitted a review, later dismissed

2020-12-10 09:53 UTC, thocle86 submitted a review, later dismissed
ok

2020-12-10 14:34 UTC, RomainClair requested changes
Composer.lock shouldn't change for no valid reason

2020-12-10 14:34 UTC, RomainClair commented on templates/base.html.twig
> +        <div class="navButton">
Should probably be a nav

2020-12-10 14:34 UTC, RomainClair commented on templates/base.html.twig
> +        <div class="othersLinksFooter">
Should probably be a nav

2020-12-10 14:34 UTC, RomainClair commented on templates/base.html.twig
> +        <div class="networkFooter">
Should also be a nav

2020-12-10 15:47 UTC, thocle86 approved these changes
ok

2020-12-11 08:23 UTC, CeliaBoiss approved these changes

2020-12-11 10:20 UTC, RomainClair approved these changes

2020-12-11 10:21 UTC, merged