Us 01 home page retouch
WildCodeSchool/tours-php-2009-project3-wewelcome pull request #15
Opened 2021-01-12 10:07 UTC by thocle86

2021-01-12 10:33 UTC, BoulMaker approved these changes, later dismissed

2021-01-12 13:27 UTC, Quentin-BLANC approved these changes, later dismissed

2021-01-12 15:37 UTC, Quentin-BLANC submitted a review, later dismissed

2021-01-12 15:58 UTC, BoulMaker submitted a review, later dismissed

2021-01-13 07:46 UTC, RomainClair requested changes
Your CSS is invalid according to w3c

2021-01-13 08:35 UTC, Quentin-BLANC approved these changes

2021-01-18 08:22 UTC, BoulMaker approved these changes

2021-01-18 08:26 UTC, RomainClair approved these changes

2021-01-18 08:26 UTC, merged