US-01_purpose_and_values
WildCodeSchool/tours-php-2009-project3-wewelcome pull request #2
Opened 2020-12-10 08:44 UTC by thocle86

Added _purpose_and_values page with css + added color variables + added client fonts

2020-12-10 09:50 UTC, Quentin-BLANC approved these changes, later dismissed

2020-12-10 10:04 UTC, FLorianBlm approved these changes, later dismissed

2020-12-10 14:12 UTC, FLorianBlm approved these changes, later dismissed

2020-12-10 14:15 UTC, CeliaBoiss submitted a review, later dismissed

2020-12-10 14:42 UTC, RomainClair requested changes
You probably should use scss only if you need it.
Use css instead when you can

2020-12-10 14:42 UTC, RomainClair commented on templates/home/_purpose_and_values.html.twig
> +        </div>
There probably should be a useless div

2020-12-10 16:39 UTC, FLorianBlm approved these changes

2020-12-11 09:19 UTC, Quentin-BLANC approved these changes

2020-12-11 11:05 UTC, RomainClair approved these changes

2020-12-11 11:05 UTC, merged