Merging dev to master
WildCodeSchool/tours-php-2009-project3-wewelcome pull request #20
Opened 2021-01-19 15:44 UTC by BoulMaker

fisrt master

2021-01-19 15:45 UTC, Quentin-BLANC approved these changes, later dismissed

2021-01-19 15:55 UTC, thocle86 submitted a review, later dismissed

2021-01-19 15:55 UTC, CeliaBoiss approved these changes, later dismissed

2021-01-20 08:30 UTC, RomainClair requested changes
I don't see any install instructions. There probably should be.
For example : you should specify that a MAILER_DSN environnement variable is needed (and maybe some others)

2021-01-21 09:14 UTC, CeliaBoiss approved these changes

2021-01-21 09:16 UTC, thocle86 approved these changes

2021-01-21 10:02 UTC, RomainClair approved these changes

2021-01-21 10:03 UTC, merged