Us1 contact coord
WildCodeSchool/tours-php-2009-project3-wewelcome pull request #4
Opened 2020-12-10 12:30 UTC by CeliaBoiss

2020-12-10 13:45 UTC, thocle86 approved these changes, later dismissed
ok

2020-12-10 14:57 UTC, Quentin-BLANC approved these changes, later dismissed

2020-12-11 09:06 UTC, FLorianBlm approved these changes, later dismissed

2020-12-11 09:11 UTC, Quentin-BLANC approved these changes

2020-12-11 09:13 UTC, Quentin-BLANC approved these changes

2020-12-11 09:13 UTC, Quentin-BLANC submitted a review, later dismissed

2020-12-11 11:18 UTC, Quentin-BLANC approved these changes, later dismissed

2020-12-11 11:18 UTC, FLorianBlm submitted a review, later dismissed

2020-12-11 13:38 UTC, Quentin-BLANC submitted a review, later dismissed

2020-12-11 13:47 UTC, thocle86 submitted a review, later dismissed
ok

2020-12-14 08:45 UTC, RomainClair requested changes
The HomeController::sendMail() private method could reasonnably be integrated in the index method

You should use twig includes when you need them.
If you don't plan to reuse the part elsewhere, it probably should be in the templates.

2020-12-14 08:45 UTC, RomainClair commented on src/FormData/MailMessageData.php
> +    private $email;
Symfony has an email constraints : https://symfony.com/doc/current/reference/constraints/Email.html

2020-12-14 08:45 UTC, RomainClair commented on src/FormData/MailMessageData.php
> +    private $phone;
You should probably check to large reasonnable maximum size

2020-12-14 08:45 UTC, RomainClair commented on templates/emails/contact.html.twig
> +    <li>Sujet : {{ message.subject }}</li>
What's the point of repeating the subject and the mail, they already are in in the mail headers !

2020-12-14 20:02 UTC, Quentin-BLANC approved these changes, later dismissed

2020-12-16 08:28 UTC, Quentin-BLANC approved these changes

2020-12-16 08:29 UTC, FLorianBlm approved these changes

2020-12-16 08:29 UTC, thocle86 approved these changes

2020-12-16 10:09 UTC, RomainClair approved these changes
You're length constraints are probably too small.
Firstname & lastnames can be longer than 50 for example.

2020-12-16 10:09 UTC, RomainClair commented on src/FormData/MailMessageData.php
> +     * @Assert\Length(max="100")
There may be valid email addresses with more than 100 caracters. A quick search tells It can be up to 254

2020-12-16 10:09 UTC, merged