Added functionality to add legal notices and cgu
WildCodeSchool/tours-php-2009-project3-wewelcome pull request #42
Opened 2021-01-28 15:41 UTC by thocle86

2021-01-28 15:46 UTC, CeliaBoiss submitted a review, later dismissed

2021-01-28 15:53 UTC, BoulMaker approved these changes, later dismissed

2021-01-29 08:55 UTC, RomainClair requested changes
Migrations not compatible with the current dev branch

2021-01-29 08:55 UTC, RomainClair commented on src/Controller/LegalsTextsController.php
> +            }
You could also have a type field in the form, may be a hidden one. Dealing with the form data would be done by the form component

2021-01-29 08:55 UTC, RomainClair commented on src/Entity/LegalsTexts.php
> +    private string $type;
You should verify your type, specially because it's one choice between a few number of choices.

2021-02-01 10:11 UTC, Quentin-BLANC approved these changes, later dismissed

2021-02-01 11:18 UTC, BoulMaker submitted a review, later dismissed

2021-02-02 09:06 UTC, RomainClair approved these changes

2021-02-02 09:08 UTC, RomainClair requested changes
Migration file incompatible with current dev branch

2021-02-02 11:18 UTC, CeliaBoiss approved these changes

2021-02-02 12:27 UTC, BoulMaker approved these changes

2021-02-02 14:15 UTC, RomainClair approved these changes

2021-02-02 14:15 UTC, merged