fix a bug that allow to register as first user without email
WildCodeSchool/tours-php-2009-project3-wewelcome pull request #50
Opened 2021-02-02 11:14 UTC by CeliaBoiss

2021-02-02 12:28 UTC, BoulMaker approved these changes, later dismissed

2021-02-02 12:49 UTC, Quentin-BLANC submitted a review, later dismissed

2021-02-02 14:13 UTC, RomainClair requested changes
Front-end validation is the optionnal one. You need a back-end validation. Without it, it is still possible to create a first user with not an email as email

2021-02-08 08:59 UTC, BoulMaker approved these changes

2021-02-08 09:18 UTC, thocle86 requested changes
I think that all the files concerning the legal texts should not be here (migrations, formType, templates, etc ...). All of this is already on the dev branch.

2021-02-08 09:42 UTC, closed without merging